version: '3.8'

services:
  next-app:
    build:
      context: ./next-app
      dockerfile: dev.Dockerfile
    container_name: next-app
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./next-app/src:/app/src
      - ./next-app/public:/app/public
      - node_modules:/app/node_modules

volumes:
  node_modules:

networks:
  default:
    name: spynet
