version: '3.8'

services:
  next:
    build:
      context: ./
      dockerfile: dev.Dockerfile
    container_name: next
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - node_modules:/app/node_modules
      - cache:/app/.next

volumes:
  node_modules:
  cache:

networks:
  default:
    name: spynet
