name: Test
concurrency: ci-${{ github.ref || github.run_id }}

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

defaults:
  run:
    working-directory: .

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          make backend-deps
      - name: Backend Jest
        run: |
          make backend-tests

  frontend-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          make frontend-deps
      - name: Frontend Jest
        run: |
          make frontend-tests
