name: Backend unit tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

defaults:
  run:
    working-directory: ./backend

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          npm install
      - name: Run tests
        run: |
          make test
